name: guided-filter
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - scipy=1.1.0
  - pillow
  - pip
  - pip:
      # guided filter
      - opencv-python
      - opencv-contrib-python
